Repository natura-cosmeticos/natds-rn, pull requests merged in 2021-02, with the labels that each got.

#138 docs(readme): adds minimal support for node on prerequisites
  README.md
  package.json
Labels: docs

#140 docs(alert): updates types of alert
  src/components/Alert/Alert.tsx
Labels: docs, support

#133 Checkbox
  package.json
  src/components/Checkbox/Checkbox.device.tsx
  src/components/Checkbox/Checkbox.stories.tsx
  src/components/Checkbox/Checkbox.styles.tsx
  src/components/Checkbox/Checkbox.test.tsx
  src/components/Checkbox/Checkbox.tsx
  src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap
  src/components/Checkbox/index.ts
  src/components/index.ts
  storybook/storyLoader.ts
Labels: component: Checkbox
